export const item = [
    {id:1,
     stock:5,
     categoria:'SILLONES',
     nombre: 'Sillón Conrad',
     descripcion: '¡Hermoso moderno y confortable sillón todo ambiente!',
     descripcion2: 'Útil y practico en la sala principal, dormitorio, sala de estar, hall, u oficina. Ideal para la lectura, ver televisión, dispositivo móvil, charlar o descansar.',
     tapizado: 'Tapizado chenille/pana/talampaya',
     tiempo:'Tiempo de entrega: entre 5 y 7 días hábiles.',
     precio:'$12000',
     imagen:'https://http2.mlstatic.com/D_NQ_NP_2X_887183-MLA33028429244_112019-F.webp' },
    
    {id:2,
    stock:3,
    categoria:'MESAS',
    nombre: 'Retro',
    descripcion: '¡Hermoso moderno y confortable sillón todo ambiente!',
    descripcion2: 'Útil y practico en la sala principal, dormitorio, sala de estar, hall, u oficina. Ideal para la lectura, ver televisión, dispositivo móvil, charlar o descansar.',
    tapizado: 'Tapizado chenille/pana/talampaya',
    tiempo:'Tiempo de entrega: entre 5 y 7 días hábiles.',
    precio:'$45000',
    imagen:'https://d2r9epyceweg5n.cloudfront.net/stores/001/656/027/products/sofa-esquinero-kansas-2-cuerpos-chenille-gris-11-c8cb203ae01ed184b716318958424032-640-0.jpg' }, 
    
    {id:3,
    stock:8,
    categoria:'SILLONES',
    nombre: 'Vicente',
    descripcion: '¡Hermoso moderno y confortable sillón todo ambiente!',
    descripcion2: 'Útil y practico en la sala principal, dormitorio, sala de estar, hall, u oficina. Ideal para la lectura, ver televisión, dispositivo móvil, charlar o descansar.',
    tapizado: 'Tapizado chenille/pana/talampaya',
    tiempo:'Tiempo de entrega: entre 5 y 7 días hábiles.',
    precio:'$38000',
    imagen:'https://d2r9epyceweg5n.cloudfront.net/stores/670/115/products/sofa_sillon_escandinavo_eggert_celeste_dos_cuerpos-hf012-2-21-b2d6d8e77c277264fb15260729458398-640-0.jpg' },
    
    {id:4,
    stock:4,
    categoria:'ALFOMBRAS',
    nombre: 'Nappe',
    descripcion: '¡Hermoso moderno y confortable sillón todo ambiente!',
    descripcion2: 'Útil y practico en la sala principal, dormitorio, sala de estar, hall, u oficina. Ideal para la lectura, ver televisión, dispositivo móvil, charlar o descansar.',
    tapizado: 'Tapizado chenille/pana/talampaya',
    tiempo:'https://i.blogs.es/aba299/sofa-convertible-escandinavo-3-plazas-rosa-claro-1000-2-21-166194_1/450_1000.jpg',
    precio:'$30000', 
    imagen:'https://i.blogs.es/aba299/sofa-convertible-escandinavo-3-plazas-rosa-claro-1000-2-21-166194_1/450_1000.jpg' }
];